/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AppController_getHello"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["UserController_getAllUsers"];
        put?: never;
        post: operations["UserController_createUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["UserController_getUser"];
        put?: never;
        post?: never;
        delete: operations["UserController_removeUser"];
        options?: never;
        head?: never;
        patch: operations["UserController_updateUser"];
        trace?: never;
    };
    "/api/users/upload-user-photo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** загрузить фото пользователя */
        post: operations["UserController_uploadUserPhoto"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/remove-user-photo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["UserController_removeUserPhoto"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/animal": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Получение списка животных
         * @description Возвращает список всех животных в системе
         */
        get: operations["AnimalsController_getAnimals"];
        put?: never;
        /**
         * Создание нового животного
         * @description Создает новую запись о животном с возможностью загрузки фотографий
         */
        post: operations["AnimalsController_createAnimal"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/animal/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Получение данных животного
         * @description Возвращает подробную информацию о конкретном животном
         */
        get: operations["AnimalsController_getAnimal"];
        put?: never;
        post?: never;
        /**
         * Удаление животного
         * @description Удаляет запись о животном из системы
         */
        delete: operations["AnimalsController_deleteAnimal"];
        options?: never;
        head?: never;
        /**
         * Обновление данных животного
         * @description Обновляет информацию о животном с возможностью загрузки новых фотографий
         */
        patch: operations["AnimalsController_updateAnimal"];
        trace?: never;
    };
    "/api/color-guide": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получения списка цветов */
        get: operations["ColorGuideController_getAllBreed"];
        put?: never;
        /** Добавление окраса животного */
        post: operations["ColorGuideController_createColor"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/color-guide/options": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Опции цветов (title=name, value=code) */
        get: operations["ColorGuideController_getColorOptions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/color-guide/{code}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Удаление окраса */
        delete: operations["ColorGuideController_removeColor"];
        options?: never;
        head?: never;
        /** Обновление окраса животного */
        patch: operations["ColorGuideController_updateColor"];
        trace?: never;
    };
    "/api/fur-guide": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получение списка типа шерсти */
        get: operations["FurGuideController_getFurList"];
        put?: never;
        /** Добавление типа шерсти животного */
        post: operations["FurGuideController_createFur"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/fur-guide/options": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Опции типа шерсти (title=name, value=code) */
        get: operations["FurGuideController_getFurOptions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/fur-guide/{code}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Удаление типа шерсти */
        delete: operations["FurGuideController_removeFur"];
        options?: never;
        head?: never;
        /** Обновление типа шерсти */
        patch: operations["FurGuideController_updateFur"];
        trace?: never;
    };
    "/api/breed-guide": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получения списка пород */
        get: operations["BreedGuideController_getBreedList"];
        put?: never;
        /** Добавление породы */
        post: operations["BreedGuideController_createBreed"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/breed-guide/options": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Опции пород (title=name, value=code) */
        get: operations["BreedGuideController_getBreedOptions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/breed-guide/{code}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Удаление породы */
        delete: operations["BreedGuideController_removeType"];
        options?: never;
        head?: never;
        /** Обновление породы */
        patch: operations["BreedGuideController_updateBreed"];
        trace?: never;
    };
    "/api/species-guide": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получение списка видов животных */
        get: operations["SpeciesGuideController_getTypeList"];
        put?: never;
        /** Добавление вида животного */
        post: operations["SpeciesGuideController_createType"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/species-guide/options": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Опции видов (title=name, value=code) */
        get: operations["SpeciesGuideController_getSpeciesOptions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/species-guide/{code}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Удаление вида животного */
        delete: operations["SpeciesGuideController_removeType"];
        options?: never;
        head?: never;
        /** Обновление вида */
        patch: operations["SpeciesGuideController_updateType"];
        trace?: never;
    };
    "/api/auth": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AuthController_loginEmail"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/refresh-token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AuthController_refreshToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AuthController_logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        UserCreateDto: {
            /**
             * @description Имя пользователя
             * @example Иван
             */
            firstName: string;
            /**
             * @description Фамилия пользователя
             * @example Фролов
             */
            lastName: string;
            /**
             * @description Email пользователя
             * @example test1@example.com
             */
            email: string;
        };
        BreedEntity: {
            id: number;
            code: string;
            name: string;
            description?: string;
            species: components["schemas"]["SpeciesEntity"];
            animals: components["schemas"]["AnimalEntity"][];
            /** Format: date-time */
            createdDate: string;
            /** Format: date-time */
            updatedDate: string;
        };
        SpeciesEntity: {
            id: number;
            code: string;
            name: string;
            description?: string;
            animals: components["schemas"]["AnimalEntity"][];
            breeds: components["schemas"]["BreedEntity"][];
            /** Format: date-time */
            createdDate: string;
            /** Format: date-time */
            updatedDate: string;
        };
        FurEntity: {
            id: number;
            code: string;
            name: string;
            description?: string;
            animals: components["schemas"]["AnimalEntity"][];
            /** Format: date-time */
            createdDate: string;
            /** Format: date-time */
            updatedDate: string;
        };
        ColorEntity: {
            id: number;
            code: string;
            name: string;
            description?: string;
            animals: components["schemas"]["AnimalEntity"][];
            /** Format: date-time */
            createdDate: string;
            /** Format: date-time */
            updatedDate: string;
        };
        AnimalPhotoEntity: {
            id: string;
            path: string;
            originalName: string;
            animal: components["schemas"]["AnimalEntity"];
            /** Format: date-time */
            createdDate: string;
            /** Format: date-time */
            updatedDate: string;
        };
        UserEntity: {
            id: number;
            firstName: string;
            lastName: string;
            middleName: string | null;
            email: string;
            phone: string;
            password: string;
            /** Format: date-time */
            birthDate: string;
            userPhoto: string;
            hashedRt: string;
            /** @enum {number} */
            role: 0 | 1 | 2;
            /** @enum {number} */
            status: 0 | 1;
            animals: components["schemas"]["AnimalEntity"][];
            /** Format: date-time */
            createdDate: string;
            /** Format: date-time */
            updatedDate: string;
        };
        AnimalEntity: {
            id: number;
            /**
             * @description НК - Новый Кот
             * @enum {string}
             */
            categoryCode: "NEW_CAT" | "NEW_DOG";
            /** @description species-id-year */
            userCode: string;
            /** @description Информация о стерилизации */
            isSpayed: boolean;
            /** @description Вид животного */
            species: components["schemas"]["SpeciesEntity"];
            /** @description Имя животного */
            name: string;
            /**
             * @description Пол животного
             * @enum {string}
             */
            gender: "MALE" | "FEMALE";
            /**
             * Format: date-time
             * @description Дата рождения животного
             * @example 2022-12-02T21:39:29.133Z
             */
            birthdate: string;
            /** @description Порода животного */
            breed: components["schemas"]["BreedEntity"];
            /** @description Тип шерсти животного */
            fur: components["schemas"]["FurEntity"];
            /** @description Окрас животного */
            color: components["schemas"]["ColorEntity"];
            /**
             * @description Статус животного
             * @enum {string}
             */
            status: "FINDING_OWNER" | "LOST" | "OWNER_FOUND" | "QUARANTINE" | "CHECK" | "RAINBOW_ROAD" | "DELETED";
            /** @description Место находки */
            placeDiscovery: string;
            /**
             * Format: date-time
             * @description Дата находки
             */
            foundDate: string;
            /** @description Особые приметы */
            specialFeatures: string | null;
            /** @description Дополнительная информация */
            furtherInformation: string;
            /** @description Нужна передержка? */
            isNeedFoster: boolean;
            /** @description Фотографии животного */
            photos: components["schemas"]["AnimalPhotoEntity"][];
            curator: components["schemas"]["UserEntity"];
            /** Format: date-time */
            createdDate: string;
            /** Format: date-time */
            updatedDate: string;
        };
        UserUpdateDto: {
            /** @example 1 */
            id?: number;
            /** @example Иван */
            firstName?: string;
            /** @example Фролов */
            lastName?: string;
            /** @example Викторович */
            middleName?: string;
            /** @example test1@example.com */
            email?: string;
            /** @example 7-999-999-99-99 */
            phone?: string;
            /**
             * Format: date-time
             * @example 25.11.2022
             */
            birthDate?: string;
        };
        CreateAnimalDto: {
            /**
             * @description НК - Новый Кот, НС - Новая Собака
             * @example НК
             * @enum {string}
             */
            categoryCode: "NEW_CAT" | "NEW_DOG";
            /**
             * @description Уникальный код животного в формате: uniqNum-species-year
             * @example 10НК-2022
             */
            userCode: string;
            /**
             * @description Код вида животного (например: cat, dog)
             * @example cat
             */
            speciesCode: string;
            /**
             * @description Кличка животного
             * @example Мурзик
             */
            name: string;
            /**
             * @description Пол животного
             * @example MALE
             * @enum {string}
             */
            gender: "MALE" | "FEMALE";
            /**
             * Format: date-time
             * @description Дата рождения животного
             * @example 2022-11-26T19:03:48.663Z
             */
            birthdate: string;
            /**
             * @description Код породы животного
             * @example british
             */
            breedCode: string;
            /**
             * @description Код типа шерсти животного
             * @example short
             */
            furCode: string;
            /**
             * @description Код окраса животного
             * @example black
             */
            colorCode: string;
            /**
             * @description Статус животного
             * @example CHECK
             * @enum {string}
             */
            status: "FINDING_OWNER" | "LOST" | "OWNER_FOUND" | "QUARANTINE" | "CHECK" | "RAINBOW_ROAD" | "DELETED";
            /**
             * @description Адрес места находки
             * @example Ленина 1
             */
            placeDiscovery?: string;
            /**
             * @description Дата находки животного
             * @example 2022-11-26T19:03:48.663Z
             */
            foundDate?: string;
            /**
             * @description Особые приметы животного
             * @example Черный хвост, белый нос
             */
            specialFeatures?: string;
            /**
             * @description Дополнительная информация о животном
             * @example Любая дополнительная информация
             */
            furtherInformation?: string;
            /**
             * @description Нужна ли передержка животному?
             * @example false
             */
            isNeedFoster: boolean;
            /** @description Фотографии животного */
            photos?: string[];
            /**
             * @description ID ответственного волонтера за животное
             * @example 1
             */
            curatorId?: number;
        };
        AnimalUpdateDto: {
            /**
             * @description Кличка животного
             * @example Мурзик
             */
            name?: string;
            /**
             * @description Пол животного
             * @example MALE
             * @enum {string}
             */
            gender?: "MALE" | "FEMALE";
            /**
             * Format: date-time
             * @description Дата рождения животного
             * @example 2022-11-26T19:03:48.663Z
             */
            birthdate?: string;
            /**
             * @description Код породы животного
             * @example british
             */
            breedCode?: string;
            /**
             * @description Код типа шерсти животного
             * @example short
             */
            furCode?: string;
            /**
             * @description Код окраса животного
             * @example black
             */
            colorCode?: string;
            /**
             * @description Статус животного
             * @example CHECK
             * @enum {string}
             */
            status?: "FINDING_OWNER" | "LOST" | "OWNER_FOUND" | "QUARANTINE" | "CHECK" | "RAINBOW_ROAD" | "DELETED";
            /**
             * @description Адрес места находки
             * @example Ленина 1
             */
            placeDiscovery?: string;
            /**
             * @description Дата находки животного
             * @example 2022-11-26T19:03:48.663Z
             */
            foundDate?: string;
            /**
             * @description Особые приметы животного
             * @example Черный хвост, белый нос
             */
            specialFeatures?: string;
            /**
             * @description Дополнительная информация о животном
             * @example Любая дополнительная информация
             */
            furtherInformation?: string;
            /**
             * @description Нужна ли передержка животному?
             * @example false
             */
            isNeedFoster?: boolean;
            /** @description Фотографии животного */
            photos?: string[];
            /**
             * @description ID ответственного волонтера за животное
             * @example 0
             */
            curatorId?: number;
        };
        CreateColorDto: {
            /**
             * @description Код окраса (уникальный)
             * @example BLACK
             */
            code: string;
            /**
             * @description Название окраса
             * @example Черный
             */
            name: string;
            /** @example Сплошной чёрный окрас */
            description?: string;
        };
        OptionDto: {
            /** @description Отображаемое название опции */
            title: string;
            /** @description Значение опции */
            value: Record<string, never>;
        };
        UpdateColorDto: {
            /**
             * @description Название окраса
             * @example Черный
             */
            name?: string;
            /** @example Сплошной чёрный окрас */
            description?: string;
        };
        CreateFurDto: {
            /**
             * @description Код типа шерсти (уникальный)
             * @example SHORT
             */
            code: string;
            /**
             * @description Название типа шерсти
             * @example Короткая
             */
            name: string;
            /** @example Короткая густая шерсть */
            description?: string;
        };
        UpdateFurDto: {
            /**
             * @description Название типа шерсти
             * @example Короткая
             */
            name?: string;
            /** @example Короткая густая шерсть */
            description?: string;
        };
        CreateBreedDto: {
            /**
             * @description Код породы (уникальный)
             * @example SCOTTISH
             */
            code: string;
            /**
             * @description Название породы
             * @example Скоттиш-фолд
             */
            name: string;
            /** @example Вислоухая кошка */
            description?: string;
            /**
             * @description Код вида животного
             * @example CAT
             */
            species: string;
        };
        UpdateBreedDto: {
            /**
             * @description Название породы
             * @example Скоттиш-фолд
             */
            name?: string;
            /** @example Вислоухая кошка */
            description?: string;
        };
        CreateSpeciesDto: {
            /**
             * @description Код вида (уникальный)
             * @example CAT
             */
            code: string;
            /**
             * @description Название вида
             * @example Кошка
             */
            name: string;
            /** @example Домашняя кошка */
            description?: string;
        };
        UpdateSpeciesDto: {
            /**
             * @description Название вида
             * @example Кошка
             */
            name?: string;
            /** @example Домашняя кошка */
            description?: string;
        };
        LoginDto: {
            /** @example test1@example.com */
            email: string;
            /** @example qwerty123 */
            password: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    AppController_getHello: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string;
                };
            };
        };
    };
    UserController_getAllUsers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserEntity"][];
                };
            };
        };
    };
    UserController_createUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserCreateDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserEntity"];
                };
            };
        };
    };
    UserController_getUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserEntity"];
                };
            };
        };
    };
    UserController_removeUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UserController_updateUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserUpdateDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserEntity"];
                };
            };
        };
    };
    UserController_uploadUserPhoto: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    file?: string;
                };
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UserController_removeUserPhoto: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string;
                };
            };
        };
    };
    AnimalsController_getAnimals: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Список животных успешно получен */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnimalEntity"][];
                };
            };
        };
    };
    AnimalsController_createAnimal: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["CreateAnimalDto"];
            };
        };
        responses: {
            /** @description Животное успешно создано */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnimalEntity"];
                };
            };
            /** @description Некорректные данные или отсутствуют обязательные поля */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AnimalsController_getAnimal: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Данные животного успешно получены */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnimalEntity"];
                };
            };
            /** @description Животное не найдено */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AnimalsController_deleteAnimal: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Животное успешно удалено */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Животное не найдено */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AnimalsController_updateAnimal: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["AnimalUpdateDto"];
            };
        };
        responses: {
            /** @description Данные животного успешно обновлены */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnimalEntity"];
                };
            };
            /** @description Некорректные данные */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Животное не найдено */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ColorGuideController_getAllBreed: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ColorEntity"][];
                };
            };
        };
    };
    ColorGuideController_createColor: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateColorDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ColorEntity"];
                };
            };
        };
    };
    ColorGuideController_getColorOptions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OptionDto"][];
                };
            };
        };
    };
    ColorGuideController_removeColor: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Окрас успешно удален. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Окрас не найден. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ColorGuideController_updateColor: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateColorDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ColorEntity"];
                };
            };
        };
    };
    FurGuideController_getFurList: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FurEntity"][];
                };
            };
        };
    };
    FurGuideController_createFur: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateFurDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FurEntity"];
                };
            };
        };
    };
    FurGuideController_getFurOptions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OptionDto"][];
                };
            };
        };
    };
    FurGuideController_removeFur: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Тип шерсти успешно удален. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Тип шерсти не найден. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    FurGuideController_updateFur: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateFurDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FurEntity"];
                };
            };
        };
    };
    BreedGuideController_getBreedList: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BreedEntity"][];
                };
            };
        };
    };
    BreedGuideController_createBreed: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateBreedDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BreedEntity"];
                };
            };
        };
    };
    BreedGuideController_getBreedOptions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OptionDto"][];
                };
            };
        };
    };
    BreedGuideController_removeType: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Порода успешно удалена. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Порода не найдена. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    BreedGuideController_updateBreed: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateBreedDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BreedEntity"];
                };
            };
        };
    };
    SpeciesGuideController_getTypeList: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpeciesEntity"][];
                };
            };
        };
    };
    SpeciesGuideController_createType: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSpeciesDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpeciesEntity"];
                };
            };
        };
    };
    SpeciesGuideController_getSpeciesOptions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OptionDto"][];
                };
            };
        };
    };
    SpeciesGuideController_removeType: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Вид успешно удален. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Вид не найден. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    SpeciesGuideController_updateType: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateSpeciesDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpeciesEntity"];
                };
            };
        };
    };
    AuthController_loginEmail: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserEntity"];
                };
            };
        };
    };
    AuthController_refreshToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": boolean;
                };
            };
        };
    };
}
